### ISSUE TITLE
Missing file and folder in example

### ISSUE THREAD

**Issue by S3nnyK** [soo-h/DASweepDetect#1]
I am following the instructions in the tutorial, but I can't find the real_data folder and the label_configure.txt file under the example folder. Should I create them myself?

**Comment by soo-h** [comment]
Thank you for reaching out and bringing this issue to our attention. The file label_configure.txt has been added to the example folder. The real_data folder should contain real genomic data for selective sweep analysis in VCF format, split by chromosome. This folder needs to be created by the user.
